In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.7.0'

Part 1 - data processing

In [3]:
# Importing the dataset
dataset = pd.read_csv('/content/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [4]:
# enhotcoding to transform male and female to 0 and 1
# label encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [5]:
# One hot encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [6]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [7]:
# Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Part 2 - Building ANN

In [8]:
# Initializing the ANN
ann = tf.keras.models.Sequential()

In [9]:
# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [10]:
# Adding the input layer and the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [11]:
# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

Part 3 - Training the ANN

In [13]:
# Compiling the ANN
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

# Training the ANN on the training set
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5186 - accuracy: 0.7958
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4612 - accuracy: 0.7964
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4414 - accuracy: 0.8002
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4300 - accuracy: 0.8080
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4229 - accuracy: 0.8129
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4179 - accuracy: 0.8134
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4134 - accuracy: 0.8145
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4099 - accuracy: 0.8141
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4066 - accuracy: 0.8151
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4036 - accura

Homework

In [14]:
# Solution
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

[[False]]


In [15]:
# Predicting the Test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [16]:
# Making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1498   97]
 [ 190  215]]


0.8565